/// Flutter icons Myapp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Myapp
///      fonts:
///       - asset: fonts/Myapp.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Myapp {
  Myapp._();

  static const _kFontFam = 'Myapp';
  static const String? _kFontPkg = null;

  static const IconData note = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_beamed = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_music = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_up = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jigsaw_piece = IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open = IconData(0xf518, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
